Algoritmo "QUESTÃO 12"
// Descrição   : Escreva um algoritmo que calcule a soma dos números de 1 a 15.
// Autor(a)    : Alan Sena
// Data atual  : 13/04/2020

Var
// Seção de Declarações das variáveis

    x,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

    PARA x DE 1 ATE 15 FACA
        soma<-soma+x
    FIMPARA

    ESCREVAL("A soma totalizou ",soma)

Fimalgoritmo