Algoritmo "QUESTÃO 2"
// Descrição   : Desenvolva um algoritmo em Pseudocódigo que imprima todos os números inteiros de 1 a 50 (em ordem decrescente).
// Autor(a)    : Alan Sena
// Data atual  : 13/04/2020

Var
// Seção de Declarações das variáveis

    x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

    PARA x DE 50 ATE 1 PASSO -1 FACA
        ESCREVAL(x)
    FIMPARA

Fimalgoritmo