Algoritmo "QUESTÃO 13"
// Descrição   : Leia o nome do usuário e escreva o nome dele na tela 10 vezes.
// Autor(a)    : Alan Sena
// Data atual  : 13/04/2020

Var
// Seção de Declarações das variáveis

    x:inteiro
    nome:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

    ESCREVAL("Informe seu nome:")
    LEIA(nome)

    PARA x DE 1 ATE 10 FACA
        ESCREVAL(nome)
    FIMPARA

Fimalgoritmo