Algoritmo "QUESTÃO 11"
// Descrição   : Escreva um algoritmo que exiba 20 vezes a mensagem “Eu gosto de estudar Algoritmos!”.
// Autor(a)    : Alan Sena
// Data atual  : 13/04/2020

Var
// Seção de Declarações das variáveis

    x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

    PARA x DE 1 ATE 20 FACA
        ESCREVAL("“Eu gosto de estudar Algoritmos!")
    FIMPARA

Fimalgoritmo